apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: emanudoc/picpay-simpleapp-python:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8008
